-- 1. Tabla para el JUEZ IA (Disputas y Veredictos)
CREATE TABLE IF NOT EXISTS disputes (
    transaction_id TEXT PRIMARY KEY,
    status TEXT NOT NULL, -- 'RESOLVED_REFUNDED', 'RESOLVED_PAID'
    verdict_json JSONB,   -- El análisis completo de la IA
    resolved_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabla para el VIGILANTE NOCTURNO (Alertas de Lavado de Dinero)
CREATE TABLE IF NOT EXISTS compliance_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id TEXT,
    type TEXT NOT NULL, -- 'AML_FRAUD_RING'
    severity TEXT,      -- 'CRITICAL', 'WARNING'
    description TEXT,
    metadata JSONB,     -- Detalles del anillo de fraude detectado
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Índices para velocidad
CREATE INDEX IF NOT EXISTS idx_disputes_status ON disputes(status);
CREATE INDEX IF NOT EXISTS idx_alerts_agent ON compliance_alerts(agent_id);
