-- Tabla de Revocación (Kill Switch)
CREATE TABLE public.revoked_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id TEXT NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    reason TEXT,
    UNIQUE(agent_id)
);

-- Tabla de Auditoría Inmutable (Caja Negra)
CREATE TABLE public.audit_trail (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    agent_id TEXT NOT NULL,
    event_type TEXT NOT NULL, -- Ej: CREDIT_DECISION, IDENTITY_ISSUE
    snapshot_data JSONB NOT NULL, -- Los datos exactos en el momento de la decisión
    integrity_hash TEXT, -- Firma criptográfica del registro
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para búsqueda rápida
CREATE INDEX idx_revoked_agent ON public.revoked_credentials(agent_id);
CREATE INDEX idx_audit_agent ON public.audit_trail(agent_id);
