import hashlib

# 1. Versión actual (Para control de cambios)
TOS_VERSION = "2026-01-06_v1.0"

# 2. El Texto Completo
MASTER_AGREEMENT_TEXT = """
AGENTPAY MASTER SERVICES AGREEMENT
Last Updated: January 6, 2026

1. PREAMBLE AND ACCEPTANCE
This Master Services Agreement ("Agreement") is a binding legal contract between AgentPay Inc. (or its applicable subsidiary, "Platform") and the individual or entity ("Client" or "Principal") accessing the AgentPay autonomous financial infrastructure.

By initializing the AgentPay() class, generating an API Key, or funding a Wallet, Client irrevocably accepts these terms. If Client is an autonomous AI Agent acting on behalf of a human, the human owner is legally presumed to have granted express authority (Agency) for this acceptance.

2. NATURE OF SERVICES (NOT A BANK)
2.1. Middleware Provider Status
Client acknowledges that AgentPay is a technology provider, not a bank. The Platform provides an API layer ("Middleware") to facilitate programmatic interactions with financial institutions.

2.2. Banking Services via Stripe
Banking, custody of funds, and card issuing services are provided by Stripe, Inc. and its banking affiliates ("Banking Partners").

Flow-Down Terms: By using AgentPay, Client agrees to be bound by the Stripe Connected Account Agreement and the Stripe Issuing Terms.

Custody: Funds displayed in the Client’s Dashboard are held in pooled custodial accounts ("FBO Accounts") maintained by Banking Partners, not by AgentPay. AgentPay never takes title to Client funds.

3. ARTIFICIAL INTELLIGENCE & VICARIOUS LIABILITY
3.1. The "Black Box" Doctrine
Client acknowledges that AI Agents (LLMs) are non-deterministic and prone to errors ("Hallucinations"). Client agrees that the Agent acts solely as a Tool under Client’s direct supervision.

3.2. Respondeat Superior (Principal Liability)
Under the legal doctrine of Respondeat Superior (Let the Master Answer):

Full Liability: Client is financially liable for 100% of all transactions executed, approved, or signed by their Agent.

No "AI Error" Defense: Client waives the right to dispute charges based on claims that "the AI made a mistake" or "the AI exceeded its prompt instructions." The failure of AgentPay's safety guardrails (ai_guard.py) does not absolve Client of payment obligations to third-party vendors.

4. "GHOST" IDENTITY & COMPLIANCE (KYC/AML)
4.1. Permitted Use: Privacy Proxy
The "Ghost Identity" features (e.g., identity.create_identity()) are provided strictly for commercial privacy (protecting Client data from vendor harvesting). AgentPay acts as Client’s Nominee for these transactions.

4.2. Prohibited Use: Synthetic Fraud
Client shall NOT use the Platform to generate "Synthetic Identities" for the purpose of:

Credit Stacking: Building fake credit history to defraud lenders.

Sanctions Evasion: Interacting with entities on the OFAC SDN List or EU Sanctions Map.

Smurfing: Structuring transactions to evade reporting thresholds. Enforcement: AgentPay maintains a "Real Identity Vault" linking every Agent to a Verified Human. This veil will be pierced immediately upon receipt of a subpoena or credible evidence of fraud.

5. ALGORITHMIC DISPUTE RESOLUTION ("AI ARBITER")
5.1. Binding Arbitration for Micro-Disputes
For disputes under $1,000 USD/EUR, Client agrees to submit to the binding resolution of the AgentPay AI Arbiter (as defined in arbitration.py). The AI Arbiter renders verdicts based on technical evidence (server logs, cryptographic hashes) rather than subjective testimony.

5.2. Human Appeal
For disputes exceeding $1,000, or where the AI Arbiter’s decision is technically flawed, Client may request a Human Compliance Review within 7 days, subject to a non-refundable administrative fee (e.g., $50).

6. ELECTRONIC SIGNATURES & NON-REPUDIATION
6.1. Validity
Any contract or order signed by the Agent using agent.sign_contract() (RSA/ECC keys) shall constitute a valid electronic signature under the US E-SIGN Act and EU eIDAS Regulation.

6.2. Non-Repudiation
Client agrees that the cryptographic logs generated by the Forensic Ledger serve as conclusive evidence of the Agent’s "Chain of Thought" and intent to transact. Client is estopped from denying the validity of such signatures.

7. INDEMNIFICATION & "KILL SWITCH"
7.1. Indemnity
Client agrees to indemnify and hold harmless AgentPay, its officers, and Banking Partners from any claims, damages, or fines arising from Client's Agent engaging in: (i) illegal purchases, (ii) copyright infringement, or (iii) denial-of-service attacks via high-frequency payments.

7.2. Emergency Suspension
AgentPay reserves the right to invoke the Kill Switch (admin.ban_agent()) without notice if:

Agent exhibits "Behavioral Drift" indicative of a cyberattack.

Client's "Z-Score" Risk Metric exceeds 5.0 standard deviations.

Required by Stripe or law enforcement.

8. GOVERNING LAW AND CLASS ACTION WAIVER
8.1. Jurisdiction
US Clients: Delaware Law. Arbitration via AAA.

EU Clients: Laws of Ireland. Jurisdiction of Dublin Courts.

8.2. Class Action Waiver
CLIENT WAIVES ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION AGAINST AGENTPAY.

(End of Legal Text)
"""

def get_current_tos_hash():
    """Genera el HASH SHA-256 único de este texto legal."""
    return hashlib.sha256(MASTER_AGREEMENT_TEXT.encode('utf-8')).hexdigest()

def get_legal_packet():
    """Devuelve el paquete completo para que el Agente lo 'lea'."""
    return {
        "version": TOS_VERSION,
        "content": MASTER_AGREEMENT_TEXT,
        "hash": get_current_tos_hash()
    }
